### PR TITLE
Update setContactDistanceThreshold to setDefaultCollisionMarginData

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@DavidMerzJr This fixes the issue using the latest Tesseract Code.

**Comment by Levi-Armstrong** [comment]
I found out why the tests are failing and I have create a [PR](https://github.com/ros-industrial-consortium/tesseract/pull/515) against Tesseract.

**Comment by DavidMerzJr** [comment]
Looks good. You can tag me when your tesseract pr is merged, and I'll merge this.

**Comment by Levi-Armstrong** [comment]
@DavidMerzJr It is now passing CI! :)

**Pull request merged**
